# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-15 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ordersdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5de5\u5382\u540d\u79f0')),
                ('product', models.CharField(max_length=20, verbose_name='\u4ea7\u54c1\u540d\u5b57')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('mobile', models.CharField(max_length=11, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('contactPerson', models.CharField(max_length=15, verbose_name='\u8054\u7cfb\u4eba')),
                ('address', models.CharField(max_length=20, verbose_name='\u5de5\u5382\u5730\u5740')),
                ('image', models.ImageField(default='', upload_to='info/%Y/%m', verbose_name='\u9884\u89c8\u56fe')),
                ('size', models.CharField(choices=[('small', '0~500\u4eba'), ('middle', '500~2000\u4eba'), ('big', '2000\u4eba\u4ee5\u4e0a')], max_length=30, verbose_name='\u5de5\u5382\u89c4\u6a21')),
                ('desc', models.TextField(max_length=1000, verbose_name='\u5de5\u5382\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5de5\u5382\u4fe1\u606f',
                'verbose_name_plural': '\u5de5\u5382\u4fe1\u606f',
            },
        ),
        migrations.AlterField(
            model_name='ordersdetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FactoryInformation', verbose_name='\u5382\u5bb6'),
        ),
    ]
