# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180415_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdetail',
            name='state',
            field=models.CharField(choices=[('\u672a\u5b8c\u6210', '\u672a\u5b8c\u6210'), ('\u5df2\u5b8c\u6210', '\u5df2\u5b8c\u6210'), ('\u5df2\u6ce8\u9500', '\u5df2\u6ce8\u9500')], default='\u672a\u5b8c\u6210', max_length=12, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
