# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180417_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdetail',
            name='capacity',
            field=models.CharField(default='', max_length=30, verbose_name='\u4f53\u79ef'),
        ),
        migrations.AddField(
            model_name='ordersdetail',
            name='weight',
            field=models.CharField(default='0kg', max_length=30, verbose_name='\u91cd\u91cf'),
        ),
    ]
