# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180418_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdetail',
            name='handler',
            field=models.CharField(default='', max_length=20, verbose_name='\u7ecf\u624b\u4eba'),
        ),
        migrations.AddField(
            model_name='ordersdetail',
            name='type',
            field=models.CharField(default='', max_length=30, verbose_name='\u4ea7\u54c1\u578b\u53f7'),
        ),
        migrations.AddField(
            model_name='ordersdetail',
            name='way',
            field=models.CharField(choices=[('\u672c\u5730\u63d0\u4ea4', '\u672c\u5730\u63d0\u4ea4'), ('\u8fdc\u7a0b\u670d\u52a1\u63d0\u4ea4', '\u8fdc\u7a0b\u670d\u52a1\u63d0\u4ea4'), ('\u4f01\u4e1a\u5185\u90e8\u63d0\u4ea4', '\u4f01\u4e1a\u5185\u90e8\u63d0\u4ea4')], default='\u672c\u5730\u63d0\u4ea4', max_length=10, verbose_name='\u63d0\u4ea4\u65b9\u5f0f'),
        ),
    ]
