# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 20:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180418_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=20, verbose_name='\u4ea7\u54c1')),
                ('count', models.CharField(default='0', max_length=20, verbose_name='\u6210\u578b\u91cf')),
                ('state', models.CharField(choices=[('\u672a\u6267\u884c', '\u672a\u6267\u884c'), ('\u6b63\u5728\u6267\u884c\u5f00\u53d1', '\u6b63\u5728\u6267\u884c\u5f00\u53d1'), ('\u9884\u53d1\u5b8c\u6210,\u6ca1\u6709\u6210\u578b', '\u9884\u53d1\u5b8c\u6210,\u6ca1\u6709\u6210\u578b'), ('\u6b63\u5728\u6267\u884c\u5b8c\u6210', '\u6b63\u5728\u6267\u884c\u5b8c\u6210'), ('\u6210\u578b\u5b8c\u6210', '\u6210\u578b\u5b8c\u6210')], default='\u672a\u6267\u884c', max_length=30, verbose_name='\u751f\u4ea7\u72b6\u6001')),
                ('raws', models.CharField(default='', max_length=20, verbose_name='\u539f\u6599\u7c7b\u578b')),
                ('weight', models.IntegerField(default=0, verbose_name='\u5bb9\u91cf')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u65f6\u95f4')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FactoryInformation', verbose_name='\u5de5\u5382')),
            ],
            options={
                'verbose_name': '\u751f\u4ea7\u4efb\u52a1',
                'verbose_name_plural': '\u751f\u4ea7\u4efb\u52a1',
            },
        ),
    ]
