# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_producetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdetail',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='\u91cd\u91cf'),
        ),
    ]
