# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180418_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdetail',
            name='way',
            field=models.CharField(choices=[('\u672c\u5730\u63d0\u4ea4', '\u672c\u5730\u63d0\u4ea4'), ('\u8fdc\u7a0b\u670d\u52a1\u63d0\u4ea4', '\u8fdc\u7a0b\u670d\u52a1\u63d0\u4ea4'), ('\u4f01\u4e1a\u5185\u90e8\u63d0\u4ea4', '\u4f01\u4e1a\u5185\u90e8\u63d0\u4ea4')], default='\u672c\u5730\u63d0\u4ea4', max_length=20, verbose_name='\u63d0\u4ea4\u65b9\u5f0f'),
        ),
    ]
