# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180418_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producetask',
            old_name='weight',
            new_name='content',
        ),
    ]
