# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180418_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producetask',
            name='content',
        ),
        migrations.AddField(
            model_name='producetask',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='\u5bb9\u91cf'),
        ),
    ]
