# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180418_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='\u91cd\u91cf')),
                ('version', models.CharField(default='', max_length=20, verbose_name='\u9884\u53d1\u4ea7\u54c1\u578b\u53f7')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6700\u665a\u5165\u4ed3\u65f6\u95f4')),
                ('model', models.CharField(default='', max_length=20, verbose_name='\u6210\u578b\u4ea7\u54c1\u578b\u53f7')),
                ('ratio', models.IntegerField(default=1, verbose_name='\u51fa\u6599\u6bd4\u4f8b')),
                ('batch', models.CharField(default='', max_length=20, verbose_name='\u6279\u53f7')),
                ('contact', models.CharField(default='', max_length=20, verbose_name='\u5173\u8054\u578b\u53f7')),
                ('color', models.CharField(default='', max_length=20, verbose_name='\u6599\u989c\u8272')),
            ],
            options={
                'verbose_name': '\u4ed3\u50a8',
                'verbose_name_plural': '\u4ed3\u50a8',
            },
        ),
    ]
