# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_storehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u540d\u79f0')),
                ('ip', models.CharField(default='', max_length=30, verbose_name='ip\u5730\u5740')),
                ('contact', models.CharField(choices=[('\u5426', '\u5426'), ('\u662f', '\u662f')], default='\u5426', max_length=5, verbose_name='\u8fde\u63a5\u72b6\u6001')),
                ('route', models.IntegerField(default=1, verbose_name='\u6240\u5904\u8def\u6bb5')),
                ('model', models.CharField(choices=[('\u624b\u52a8', '\u624b\u52a8'), ('\u81ea\u52a8', '\u81ea\u52a8')], default='\u624b\u52a8', max_length=10, verbose_name='\u624b\u52a8/\u81ea\u52a8\u6a21\u5f0f')),
                ('load', models.CharField(choices=[('\u5426', '\u5426'), ('\u662f', '\u662f')], default='\u5426', max_length=10, verbose_name='\u662f\u5426\u8d1f\u8f7d')),
                ('task', models.CharField(default='', max_length=20, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('stage', models.IntegerField(choices=[(-1, '\u65e0\u4efb\u52a1\u7a7a\u95f2'), (0, '\u6709\u4efb\u52a1\u4f46\u8fd8\u672a\u6267\u884c'), (1, '\u6682\u505c\u6267\u884c'), (2, '\u6b63\u5728\u6267\u884c\u7b2c\u4e00\u9636\u6bb5fromNode'), (3, '\u6b63\u5728\u6267\u884c\u7b2c\u4e8c\u9636\u6bb5fromMotion'), (4, '\u6b63\u5728\u6267\u884c\u7b2c\u4e09\u9636\u6bb5toNode'), (5, '\u6b63\u5728\u6267\u884c\u7b2c\u56db\u9636\u6bb5toMotion'), (6, '\u4efb\u52a1\u5df2\u7ecf\u5b8c\u6210'), (7, '\u65e0\u4efb\u52a1\u81ea\u52a8\u884c\u8d70\u5230\u5145\u7535\u533a')], default=-1, verbose_name='\u4efb\u52a1\u6267\u884c\u9636\u6bb5')),
                ('error', models.IntegerField(choices=[(0, '\u65e0\u9519\u8bef'), (1, '\u6fc0\u5149\u96f7\u8fbe\u62a5\u8b66'), (2, '\u89e6\u8fb9\u62a5\u8b66'), (3, '\u7d27\u6025\u5f00\u5173\u62a5\u8b66')], default=0, verbose_name='\u9519\u8bef\u62a5\u8b66\u72b6\u6001')),
                ('power', models.IntegerField(default=100, verbose_name='\u7535\u6c60\u72b6\u6001')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'AGV\u5c5e\u6027\u4e0e\u72b6\u6001',
                'verbose_name_plural': 'AGV\u5c5e\u6027\u4e0e\u72b6\u6001',
            },
        ),
        migrations.AlterModelOptions(
            name='storehouse',
            options={'verbose_name': '\u8d27\u4ed3\u5b58\u50a8', 'verbose_name_plural': '\u8d27\u4ed3\u5b58\u50a8'},
        ),
    ]
